apiVersion: v1
kind: ConfigMap
metadata:
  name: php-service-config
  namespace: obi-demo
data:
  MYSQL_HOST: "mysql"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "demo123"
  MYSQL_DB: "obidemo"
  MONGO_URL: "mongodb://mongodb:27017"
  SLOW_DELAY: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-service
  namespace: obi-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-service
  template:
    metadata:
      labels:
        app: php-service
    spec:
      containers:
      - name: php-service
        image: registry.cn-hangzhou.aliyuncs.com/private-mesh/obi:php-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: php-service-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: obi-demo
spec:
  selector:
    app: php-service
  ports:
  - port: 8083
    targetPort: 8083