apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-service-config
  namespace: obi-demo
data:
  REDIS_ADDR: "redis:6379"
  MONGO_URL: "mongodb://mongodb:27017"
  CPP_SERVICE_URL: "http://cpp-service:8086"
  GO_HTTP_ADDR: "http://go-service:8084"
  NODEJS_HTTP_ADDR: "http://nodejs-service:8082"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-service
  namespace: obi-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-service
  template:
    metadata:
      labels:
        app: dotnet-service
    spec:
      containers:
      - name: dotnet-service
        image: obi-demo/dotnet-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: dotnet-service-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: obi-demo
spec:
  selector:
    app: dotnet-service
  ports:
  - port: 8085
    targetPort: 8085